apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: discover
  labels:
    app: mysql
spec:
      containers:
        - name: mysql
          image: mysql/mysql-server
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "tcs123"
            - name: MYSQL_USER
              value: "sa"
            - name: MYSQL_PASSWORD
              value: "tcs123"
            - name: MYSQL_DATABASE
              value: sample
          imagePullPolicy: Never